
package com.tulingchain.soap.schema.read;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Application", targetNamespace = "com.examples.rpc")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Application {


    /**
     * 
     *         ��ȡ��Կ
     *         ���룺��
     *         �������Կ��˽Կ
     *         
     * 
     * @return
     *     returns com.tulingchain.soap.schema.KeyPair
     */
    @WebMethod(operationName = "get_key_pair", action = "get_key_pair")
    @WebResult(name = "get_key_pairResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "get_key_pair", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetKeyPair")
    @ResponseWrapper(localName = "get_key_pairResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetKeyPairResponse")
    public KeyPair getKeyPair();

    /**
     * 
     *         ��ݽ���id��ѯ���߶�
     *         ���룺����id
     *         ��������߶�
     *         
     * 
     * @param txId
     * @return
     *     returns java.math.BigInteger
     */
    @WebMethod(operationName = "get_block_height_by_tx_id", action = "get_block_height_by_tx_id")
    @WebResult(name = "get_block_height_by_tx_idResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "get_block_height_by_tx_id", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetBlockHeightByTxId")
    @ResponseWrapper(localName = "get_block_height_by_tx_idResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetBlockHeightByTxIdResponse")
    public BigInteger getBlockHeightByTxId(
        @WebParam(name = "tx_id", targetNamespace = "com.examples.rpc")
        String txId);

    /**
     * 
     *         ��ѯ�²���Ľ��ף�ÿ���Ӹ���һ�Σ�
     *         ���룺��
     *         ���������ҵ����ţ� ���׷��𷽵�ַ�� ���׽��ܷ���ַ��  TransactionID, WorkID, ����ʱ��
     *         
     * 
     * @return
     *     returns com.tulingchain.soap.schema.LastTx
     */
    @WebMethod(operationName = "get_last_tx", action = "get_last_tx")
    @WebResult(name = "get_last_txResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "get_last_tx", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetLastTx")
    @ResponseWrapper(localName = "get_last_txResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetLastTxResponse")
    public LastTx getLastTx();

    /**
     * 
     *         ��Դ
     *         ���룺��Ʒ��Կ
     *         �������������
     *         
     * 
     * @param publicKey
     * @return
     *     returns com.tulingchain.soap.schema.StringArray
     */
    @WebMethod(operationName = "trace_transactions", action = "trace_transactions")
    @WebResult(name = "trace_transactionsResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "trace_transactions", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.TraceTransactions")
    @ResponseWrapper(localName = "trace_transactionsResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.TraceTransactionsResponse")
    public StringArray traceTransactions(
        @WebParam(name = "public_key", targetNamespace = "com.examples.rpc")
        String publicKey);

    /**
     * 
     *         ��ݽ���id��ѯ�����Ϣ
     *         ���룺����id
     *         ��������������Ϣ
     *         
     * 
     * @param txId
     * @return
     *     returns com.tulingchain.soap.schema.BigBlock
     */
    @WebMethod(operationName = "get_block_by_tx_id", action = "get_block_by_tx_id")
    @WebResult(name = "get_block_by_tx_idResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "get_block_by_tx_id", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetBlockByTxId")
    @ResponseWrapper(localName = "get_block_by_tx_idResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetBlockByTxIdResponse")
    public BigBlock getBlockByTxId(
        @WebParam(name = "tx_id", targetNamespace = "com.examples.rpc")
        String txId);

    /**
     * 
     *         ��鴴��Create����
     *         ���룺��Կ����Ա���ص㣬ʱ�䣬��Ʒ
     *         ���������id
     *         
     * 
     * @param publicKey
     * @param when
     * @param where
     * @param thing
     * @param who
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "create_transaction", action = "create_transaction")
    @WebResult(name = "create_transactionResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "create_transaction", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.CreateTransaction")
    @ResponseWrapper(localName = "create_transactionResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.CreateTransactionResponse")
    public String createTransaction(
        @WebParam(name = "public_key", targetNamespace = "com.examples.rpc")
        String publicKey,
        @WebParam(name = "who", targetNamespace = "com.examples.rpc")
        Who who,
        @WebParam(name = "where", targetNamespace = "com.examples.rpc")
        Where where,
        @WebParam(name = "when", targetNamespace = "com.examples.rpc")
        When when,
        @WebParam(name = "thing", targetNamespace = "com.examples.rpc")
        Thing thing);

    /**
     * 
     *         ������Height��ѯ�����Ϣ
     *         ����: Block_Height
     *         ����������������Ϣ
     *         
     * 
     * @param height
     * @return
     *     returns com.tulingchain.soap.schema.BigBlock
     */
    @WebMethod(operationName = "get_block_by_height", action = "get_block_by_height")
    @WebResult(name = "get_block_by_heightResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "get_block_by_height", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetBlockByHeight")
    @ResponseWrapper(localName = "get_block_by_heightResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetBlockByHeightResponse")
    public BigBlock getBlockByHeight(
        @WebParam(name = "height", targetNamespace = "com.examples.rpc")
        BigInteger height);

    /**
     * 
     *         �������ַ��ѯ�����Ϣ
     *         ���룺����ַ
     *         ����� �õ�ַ���н�����Ϣ
     *         
     * 
     * @param addr
     * @return
     *     returns com.tulingchain.soap.schema.TransactionArray
     */
    @WebMethod(operationName = "get_txs_by_block_addr", action = "get_txs_by_block_addr")
    @WebResult(name = "get_txs_by_block_addrResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "get_txs_by_block_addr", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetTxsByBlockAddr")
    @ResponseWrapper(localName = "get_txs_by_block_addrResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetTxsByBlockAddrResponse")
    public TransactionArray getTxsByBlockAddr(
        @WebParam(name = "addr", targetNamespace = "com.examples.rpc")
        String addr);

    /**
     * 
     *         �����齻��ID��ѯ������Ϣ
     *         ���룺 TransactionID
     *         ����� �ñʽ���������Ϣ
     *         
     * 
     * @param id
     * @return
     *     returns com.tulingchain.soap.schema.Data
     */
    @WebMethod(operationName = "get_tx_by_id", action = "get_tx_by_id")
    @WebResult(name = "get_tx_by_idResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "get_tx_by_id", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetTxById")
    @ResponseWrapper(localName = "get_tx_by_idResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetTxByIdResponse")
    public Data getTxById(
        @WebParam(name = "id", targetNamespace = "com.examples.rpc")
        String id);

    /**
     * 
     *         ��ѯ�²������飨ÿ���Ӹ���һ�Σ�
     *         ���룺��
     *         ��������߶ȣ� TransactionID,  node_pubkey, WorkID, ������ʱ��
     *         
     * 
     * @return
     *     returns com.tulingchain.soap.schema.LastBlock
     */
    @WebMethod(operationName = "get_last_block", action = "get_last_block")
    @WebResult(name = "get_last_blockResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "get_last_block", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetLastBlock")
    @ResponseWrapper(localName = "get_last_blockResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.GetLastBlockResponse")
    public LastBlock getLastBlock();

    /**
     * 
     *         ����Transfer����
     *         ���룺���׷��𷽹�Կ�����׽��շ���Կ�����׷���˽Կ����Ա���ص㣬ʱ�䣬��Ʒ
     *         ���������id��ʣ����Ʒ����Կ
     *         
     * 
     * @param txRecipientPublicKey
     * @param when
     * @param txOriginatorPrivateKey
     * @param txOriginatorPublicKey
     * @param where
     * @param thing
     * @param who
     * @return
     *     returns com.tulingchain.soap.schema.TransferResult
     */
    @WebMethod(operationName = "transfer_transaction", action = "transfer_transaction")
    @WebResult(name = "transfer_transactionResult", targetNamespace = "com.examples.rpc")
    @RequestWrapper(localName = "transfer_transaction", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.TransferTransaction")
    @ResponseWrapper(localName = "transfer_transactionResponse", targetNamespace = "com.examples.rpc", className = "com.tulingchain.soap.schema.TransferTransactionResponse")
    public TransferResult transferTransaction(
        @WebParam(name = "tx_originator_public_key", targetNamespace = "com.examples.rpc")
        String txOriginatorPublicKey,
        @WebParam(name = "tx_recipient_public_key", targetNamespace = "com.examples.rpc")
        String txRecipientPublicKey,
        @WebParam(name = "tx_originator_private_key", targetNamespace = "com.examples.rpc")
        String txOriginatorPrivateKey,
        @WebParam(name = "who", targetNamespace = "com.examples.rpc")
        Who who,
        @WebParam(name = "where", targetNamespace = "com.examples.rpc")
        Where where,
        @WebParam(name = "when", targetNamespace = "com.examples.rpc")
        When when,
        @WebParam(name = "thing", targetNamespace = "com.examples.rpc")
        Thing thing);

}
