angular.module('myApp',[
    'ngRoute','ngAnimate','ui.bootstrap', 'BlockChainAdminController','HomeController',
    'controllers', 'myFilters','ngCookies',
    'myServices', 'myDirectives','ngMessages' ])

   .config(function($routeProvider){
    $routeProvider.when('/case',{
	   templateUrl:'tpls/case.html',
	   controller:'homeController'
    }).when('/aboutus',{
       templateUrl:'tpls/aboutus.html',
       //controller:'ScrollController'
    }).when('/trace',{
        templateUrl:'tpls/trace.html',
        controller:'traceController'
     }).when('/solution',{
       templateUrl:'tpls/solution.html',
       //controller:'ScrollController'
    }).when('/principle',{
       templateUrl:'tpls/principle.html',
       //controller:'ScrollController'
    }).when('/bbs',{
       templateUrl:'tpls/bbs.html',
       //controller:'ScrollController'
    }).when('/fq',{
       templateUrl:'tpls/fq.html',
       //controller:'ScrollController'
    }).when('/contactus',{
       templateUrl:'tpls/contactus.html',
       //controller:'ScrollController'
    }).when('/login',{
       templateUrl:'tpls/login.html',
       controller:'UserController'
    }).when('/register',{
       templateUrl:'tpls/register.html',
       controller:'UserController'
    }).when('/userInfo',{
       templateUrl:'tpls/userInfo.html',
       reloadOnSearch: true,
       controller:'UserInfoController'
    }).when('/noderInfo',{
       templateUrl:'tpls/noderInfo.html',
       controller:'NoderInfoController'
    }).when('/apply',{
       templateUrl:'tpls/apply.html',
    }).when('/purchase',{
       templateUrl:'tpls/purchase.html',
       controller:'PurcController'
    }).when('/sellerRawmPurchaseList',{
       templateUrl:'tpls/purchaseRawnRecord.html',
       controller:'NoderPurcController'
    }).when('/sellerProdPurchaseList',{
       templateUrl:'tpls/purchaseProdRecord.html',
       controller:'NoderPurcController'
    }).when('/rawmaterial/:id',{
       templateUrl:'tpls/rawmaterial.html',
       controller:'NoderRawmController'
    }).when('/rawmaterialList',{
       templateUrl:'tpls/rawmaterialRecord.html',
       controller:'NoderRawmController'
    }).when('/rawmaterialInfo/:id',{
       templateUrl:'tpls/rawmaterialInfo.html',
       controller:'RawmInfoController'
    }).when('/transRawmList',{
	   templateUrl:'tpls/rawmTransList.html',
	   controller:'TransRController'
    }).when('/deliveryList',{
	   templateUrl:'tpls/deliveryList.html',
	   controller:'RawmProdDeliveryController'
    }).when('/transAllList',{
	   templateUrl:'tpls/transportList.html',
	   controller:'TransController'
    }).when('/product/:id',{
	   templateUrl:'tpls/product.html',
	   controller:'NoderProdController'
    }).when('/productList',{
	   templateUrl:'tpls/productRecord.html',
	   controller:'NoderProdController'
    }).when('/productInfo/:id',{
	   templateUrl:'tpls/productInfo.html',
	   controller:'ProdInfoController'
    }).when('/transProdList',{
	   templateUrl:'tpls/prodTransList.html',
	   controller:'TransPController'
    }).when('/rawmTransport/:id',{
	   templateUrl:'tpls/rawmTransport.html',
	   controller:'TransRawmController'
    }).when('/prodTransport/:id',{
	   templateUrl:'tpls/prodTransport.html',
	   controller:'TransProdController'
    }).when('/transList',{
	   templateUrl:'tpls/delivery.html',
	   controller:'DeliveryController'
    }).when('/transDelivery/:id',{
       templateUrl:'tpls/deliveryInfo.html',
       controller:'DeliveryInfoController'
    }).when('/block',{
       templateUrl:'tpls/blockInfo.html',
       controller:'BlockInfoController'
    }).when('/transaction',{
       templateUrl:'tpls/bill_transaction.html',
       controller:'TransactionInfoController'
    }).when('/newNodeApply',{
        templateUrl:'tpls/newNodeApply.html',
        controller:'newNodeApplyController'
     }).when('/newNodeApplyRecord',{
         templateUrl:'tpls/newNodeApplyRecord.html',
         controller:'newNodeApplyRecordController'
     }).when('/newNodeApplyRecordInfo/:userNameID/:nodeID',{
         templateUrl:'tpls/newNodeApplyInfo.html',
         controller:'newNodeApplyRecordInfoController'
     }).when('/register',{
         templateUrl:'tpls/register.html',
         controller:'newNodeApplyController'
     })
     .when('/moreBlockInfo/:currentPage',{
    	templateUrl: 'tpls/moreBlockInfo.html',
    	controller: 'MoreBlockInfoController'
    }).otherwise({
       redirectTo:'/case',
       controller:'BlockChianController'
    })
})