
package com.tulingchain.soap.schema.write;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RpcService", targetNamespace = "com.examples.rpc", wsdlLocation = "http://120.27.158.8:8000/rpc/wsdl/")
public class RpcService
    extends Service
{

    private final static URL RPCSERVICE_WSDL_LOCATION;
    private final static WebServiceException RPCSERVICE_EXCEPTION;
    private final static QName RPCSERVICE_QNAME = new QName("com.examples.rpc", "RpcService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://120.27.158.8:8000/rpc/wsdl/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RPCSERVICE_WSDL_LOCATION = url;
        RPCSERVICE_EXCEPTION = e;
    }

    public RpcService() {
        super(__getWsdlLocation(), RPCSERVICE_QNAME);
    }

    public RpcService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RPCSERVICE_QNAME, features);
    }

    public RpcService(URL wsdlLocation) {
        super(wsdlLocation, RPCSERVICE_QNAME);
    }

    public RpcService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RPCSERVICE_QNAME, features);
    }

    public RpcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RpcService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication() {
        return super.getPort(new QName("com.examples.rpc", "Application"), Application.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication(WebServiceFeature... features) {
        return super.getPort(new QName("com.examples.rpc", "Application"), Application.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RPCSERVICE_EXCEPTION!= null) {
            throw RPCSERVICE_EXCEPTION;
        }
        return RPCSERVICE_WSDL_LOCATION;
    }

}
